 export const products = [
    "Apple",
    "Banana",
    "Cherry",
    "Date",
    "Elderberry",
    "Fig",
    "Grape",
    "Honeydew",
    "Kiwi",
    "Lemon",
    "Mango",
    "Nectarine",
    "Orange",
    "Papaya",
    "Quince",
    "Raspberry",
    "Strawberry",
    "Tangerine",
    "Ugli fruit",
    "Watermelon",
    "Apricot",
    "Blueberry",
    "Cantaloupe",
    "Dragonfruit",
    "Eggplant",
    "Fennel",
    "Grapefruit",
    "Huckleberry",
    "Jackfruit",
    "Kumquat",
    "Lime",
    "Melon",
    "Nashi pear",
    "Olive",
    "Peach",
    "Rambutan",
    "Star fruit",
    "Tomato",
    "Ugni",
    "Vanilla",
    "White currant",
    "Xigua",
    "Yellow watermelon",
    "Zucchini",
    "Almond",
    "Brazil nut",
    "Cashew",
    "Date palm",
    "Elderflower",
    "Figs",
    "Ginger",
    "Hazelnut",
    "Indian gooseberry",
    "Jujube",
    "Kola nut",
    "Lemonade fruit",
    "Mandarin",
    "Nutmeg",
    "Oregano",
    "Parsley",
    "Quinoa",
    "Raisin",
    "Saffron",
    "Tamarind",
    "Urad bean",
    "Vanilla bean",
    "Walnut",
    "Xigua fruit",
    "Yam",
    "Zucchini flower",
    "Anise",
    "Basil",
    "Cinnamon",
    "Dill",
    "Eucalyptus",
    "Fennel seed",
    "Ginger root",
    "Hibiscus",
    "Juniper berry",
    "Kaffir lime",
    "Lavender",
    "Mint",
    "Nigella",
    "Olive oil",
    "Parsnip",
    "Rosemary",
    "Sage",
    "Thyme",
    "Urad dal",
    "Vanilla extract",
    "Wasabi",
    "Xacuti",
    "Yarrow",
    "Za'atar"
  ];